language: python
python:
  - '3.6'
install: pip install -r requirements.txt
script: python3 -m unittest
deploy:
  provider: pypi
  user: "professormahi_f"
  password:
    secure: "ILRJKWT6lscG+kX5vqSXx7G3ffDf6POzkV990eeSJGweV+nqP1+wV9zOACPesmEpIiUacP+0OyfFWsQp40Vb8k5YDl1DA+sd3AhWhiXonOLNZabAC6ReGii3p+UQYc0WkSY0Q3dvPVVBdNXC/ddYbE/74WhD8zrL/UlN7TO7t+vt7eisX/3MlyFUk5xN2ArudSzXoxpPL868mC0rzho+A9FztV8L1R1rqNOkUoW4xSVRT8DKYl5rTk5xgotglYIIyaM5BewASd7KcYiYuIF+cyX5Np1/NZq7EwLdsu/CNesJ5C/WJ3+9obxkWCdm/CJnhu37ku9IznJekJsWMdo9/cU/1JYIHeC3sNJ214o+NeOiz99x5henFL7+MY5+s3OsUrqVisHcdgtCisvudabThCc4YpwASftwl5huNx/LXTiQLQ5B16Bs7OqtcrVsVuVxOQNVzuw2/pM8PoAK6GCyvn134eUfWGe28fFC62XbrQqQXmfBsgxiWE09vhSdK6H8hP+HVTnb03xt9eCb1fYUrVmQ5Qymzt4CUwmEm1S3kCsBXHwK7+K/RHKKI3D1N0OMNvl1KgTU+/QxKmK+GmGTSMpKB/HYkJ1Ezi4ksAUYrAcmLWrbyXBqQcTv5ZuDK8QGwKxyM6ynz0+qbYCCWVgEH+c91aNgBH7iRoQcvDtJJcQ="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
